### ISSUE TITLE
Write to disk

### ISSUE THREAD

**Issue by jakiki6** [sugarfi/C8#3]
"exit protected mode and write to disk"
I actually used that in another os. It's not a great idea because the BIOS isn't reliable and you don't have control over the device and it is really slow.

I would suggest to write an ata/ahci driver.
I'll try doing that :)

**Comment by jakiki6** [comment]
Ok it looks like you have a ATA PIO driver so why did you write that?

**Comment by sugarfi** [comment]
> so why did you write that?

yeah, sorry about that - it's a bit outdated.
